services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mvp
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata: {}
